# пример файла конфигурации
[logger]                # настройка логгера
    mode = "prod"       # режим (prod или dev или debug)
    enable = true       # активация логгера
    timestamp = "none"  # выводить время лога (none, time или full)
    type = true         # выводить тип лога (true или false)

[authorization]                     # настройка авторизации
    [[authorization.users]]         # массив пользователей
        username = "username"       # имя пользователя
        password = "password"       # пароль пользователя
    [[authorization.users]]         
        token = "xxxxxxxxxxxx"      # токен доступа

[api]                                   # настройка API
    enable = false                      # активация API
    auth = false                        # активация авторизации
    listening = "*:3001"                # настройка слушателя
    prefix = "/api"                     # префикс
    proxy = false                       # когда поле заголовка true proxy будут доверенным
    subdomain_offset = 2                # смещение от поддомена для игнорирования
    proxy_header = "X-Forwarded-For"    # заголовок IP прокси
    ips_count = 0                       # максимальное количество IP прочитанное из заголовка прокси, по умолчанию 0 (означает бесконечность)
    env = "development"                 # среда для сервера koa
    #keys = []                          # массив подписанных ключей cookie
    [api.parsing]                       # настройка парсинга (пакет: https://github.com/dlau/koa-body#readme)
        enable = false                  # активация парсинга
        encoding = "utf-8"              # кодировка парсинга
        form_limit = "56kb"             # лимит для форм
        json_limit = "1mb"              # лимит для json
        text_limit = "1mb"              # лимит для raw
        text = true                     # парсинг raw
        json = true                     # парсинг json
        multipart = false               # парсинг составных частей
        include_unparsed = false        # добавить исходное тело запроса в переменную ctx.request.body
        urlencoded = true               # парсинг данных urlencoded
        json_strict = true              # строгий режим парсинга json
        methods = ["POST"]              # список методов для парсинга

[[mock]]                                    # массив настроек mock серверов
    name = "my_name_mock"                   # имя mock сервера, должно быть уникальным
    enable = true                           # активация mock сервера
    thread = ""                             # имя потока (НЕ ОБЯЗЯТЕЛЬНА)
    state_path = "state"                    # папка/файл в формате json/toml/yml начального состояния сервера (НЕ ОБЯЗЯТЕЛЬНА)
    routes_path = "routes"                  # папка с маршрутами
    handlers_path = "handlers"              # папка с процессорами
    v_host = "/"                            # виртуальный хост
    reconnect_interval = 10                 # интервал переподключения
    url = "guest:guest@localhost:5672"      # строка подключения
    heartbeat = 30                          # сердцебиение
    [mock.input]                                # настройка входа
        parallel = 1                            # количество параллельных запросов
        codec = "json"                          # кодек разбора сообщения (json, text или buffer)
        fast_ack = true                         # подтверждение сразу после получения сообщения
        #v_host = "/"                           # виртуальный хост
        #reconnect_interval = 10                # интервал переподключения
        #url = "guest:guest@localhost:5672"     # строка подключения
        #heartbeat = 30                         # сердцебиение
        [mock.input.queue]                      # настройка очереди
            name = ""                           # имя очереди
            pattern = ""                        # паттерт для маршрутизации
            [mock.input.queue.options]          # параметры rabbitmq для очереди
                autoDelete = false             
                durable = true                 
        [mock.input.exchange]                   # настройки точки обмена не обязательно (НЕ ОБЯЗЯТЕЛЬНА)
            name = "logs"                       # имя точки обмена
            type = "fanout"                     # тип точки обмена
            [mock.input.exchange.options]       # параметры точки обмена для rabbitmq
                durable = true
                autoDelete = false
    [mock.output]                               # настройка выхода
        #v_host = "/"                           # виртуальный хост
        #reconnect_interval = 10                # интервал переподключения
        #url = "guest:guest@localhost:5672"     # строка подключения
        #heartbeat = 30                         # сердцебиение
        [mock.output.default]                   # значения по умолчанию для маршрутов
            type = "exchange"                       # тип точки назначения (queue или exchange)
            destination = ""                        # имя точки назначения
            routing_key = ""                        # ключ маршрутизации
            [mock.output.default.options]           # настройки сообщений
                persistent = true